Feature/swg2 diagnosticreport radiology
jami-fhir-jp-wg/jp-core-v1x pull request #295
Opened 2022-08-17 08:16 UTC by HERMITRION

## 修正内容
1) urlの修正 http -> https 等　一部リンク切れの修正を含む．
本家から自動取得されるバリューセットのリンク切れは未修正．

2) プロファイル表記の調整．日本語化されている部分はできるだけ英語を削除した．

3) CommonとRadiolgyの役割分担の明確化．特にプロファイルにおいてcommonと異なる点はradiolgyで再定義した．
（プロファイルの修正はもう少し手を加える必要はあると思っています．）

4) 外部リンクのエイリアスを設定（お試し利用してみた．）

## Merge依頼先

SWG2
宮川さんお願いします．

## レビュー観点

特にリンク関係で不整合が無いか，プロファイルの編集で問題が生じていないかをご確認いただければと思います．

## 関連ISSUE

## 補足

2022-08-17 09:49 UTC, findex-miyakawa requested changes
一部競合の部分の修正にて、消えてしまった部分があるので、修正します。

2022-08-18 01:27 UTC, HERMITRION commented
宮川さん修正をmergeしたつもりですが，gitの使い方にまだ慣れていないので，もし不整合が生じていたらすみません．

2022-08-18 02:07 UTC, findex-miyakawa approved these changes

2022-08-18 07:29 UTC, HERMITRION commented
平山さん　pull requestの後にもいろいろ変更した状態で同期をかけていますので、少しチェックがややこしくなってしまったかもしれません．申し訳ありませんが，ご確認のほどよろしくお願いいたします．

2022-08-19 23:14 UTC, kis-hirayama approved these changes
確認いたしました。

2022-08-19 23:15 UTC, kis-hirayama commented
@HERMITRION 
田中先生
ご対応ありがとうございました。

2022-08-19 23:15 UTC, merged