JP_Observation_PhysicalExam（身体所見）プロファイルを修正
jami-fhir-jp-wg/jp-core-v1x pull request #424
Opened 2022-09-03 22:55 UTC by kis-hirayama

## 修正内容
- 診察方法のCodeSystem（ドラフト）を作成
- 説明を追記

## Merge依頼先

@findex-miyakawa 

## レビュー観点

## 関連ISSUE

fixed #356 

## 補足
ご確認お願い致します。

2022-09-04 01:43 UTC, findex-miyakawa requested changes
bodysite,methodについては良いと思います。

気になっているのは以下の２点です。
１）codeのバインディング強度がrequiredおよびコードが１つ固定されている。
fhir baseのpysical examの例を見る限り、codeによって何の所見かを切り分けるようにしている。またrequiredによって独自に各学会等で所見についてマスタを作ろうとしてもこれを許さない構造になっているようにみえます。

２）value[x]がyes,no型に固定されている。
所見等の自由記載もできない形になっています。
[phyxam](https://www2.medis.or.jp/master/syoken/phyxam-beta_20140306.xls)の例を見ても、論理型以外にも、選択肢、文字列、図示等の型があり、これらの記述も否定することになります。

★fhir baseの例
https://hl7.org/fhir/r4/observation-examples.html#10.1.7.2

一度口頭で話をしませんか？
意図を取り違えているだけならよいのですが。

2022-09-04 15:09 UTC, kis-hirayama commented
ご確認ありがとうございます。
また、ご質問に対する回答ができておらず申し訳ございません。

まず、大前提としてSWG2で検討している各プロファイルにつきましては、ユースケース毎に特化したプロファイル（厚生労働省標準のFHIR記述仕様で策定される予定のプロファイルなどと同等の位置づけ）になります。（※全体WGでも過去に報告済み）
また、FHIR基底仕様のプロファイルが国内利用に必ずしも当てはまるとは限りませんので、SWG2ではそれに引きずられないよう各専門領域の先生方のご意見をお聞きしながら議論を進めてまいりました。
各学会様等で独自のプロファイルを策定したい場合には、汎化したCommonプロファイルからの派生プロファイルになるのではないでしょうか。
なお、これもすでに全体WGでお話があったかと思いますが、研究用途も視野に入れつつまずは診療ベースのプロファイル策定という方針でよかったかと存じます。
ですので、一度SWG1でご検討いただき、再度全体WGで各SWGに方針を提示していただいた上でSWG毎で齟齬のないように今後進めさせていただけますと幸いです。

2022-09-05 01:43 UTC, findex-miyakawa commented
ちなみに拡張にオープンな作りにするには下記の対応があればよいと考えています。
修正としては簡易です。

【現状】
1)code, component.codeのバインドレベル:required
2)value[x]をCodeableConceptに限定
3)valueCodeableConceptのバインドレベル:required

【修正案】
・code, component.codeのバインドレベル:prefered
・value[x] onlyによる限定を削除
・CodeableConceptの例として
　valueCodebleConcept from $v2-0136 (preferred)

2022-09-09 14:37 UTC, kis-hirayama commented
@findex-miyakawa 
宮川さま
ご返信が遅くなり申し訳ございません。
私自身、何が正か不明瞭な状態に陥ってしまっておりましたので、まずは弊社内で認識合わせを行い、
不明点が解消されましたので、SWG2リーダーの塩川さんにも状況を説明した上で、ご回答をいただきました。
なお、塩川さんがGitHubのアカウントをお持ちでないとのことですので、代理で回答させていただきます。

```
SWG2はObservationという汎用的で特殊なリソースを扱う性質上、ユースケースを
ベースに検討を行い、そこから共通部分を拾い出して、commonとし、JP Coreの
リソース要件にする方針です。
したがって、現状のSWG2でのユースケース毎の要件はJP Coreの要件として、とで
はなく、平山さんのお考えの通り、その1つ上のレベルか、（大江先生のお考えだと、
1つ上のレベルはかなり大雑把な、例えば診療用、とか研究用ユースケース、という話
なので、）2つ上のレベルの定義になろうかと思います。
よって、今回のV1.1での対応としては、宮川さんのおっしゃるようなcommonに緩い
レベルでの集約、で構わないと思います。
```
結論としましては、宮川さまのご提案通りに修正させていただきます。

2022-09-12 01:25 UTC, merged